# Generated by Django 4.0.5 on 2022-06-16 07:47

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('formatted_address', models.CharField(max_length=96, unique=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True)),
                ('zip_code', models.CharField(max_length=5)),
                ('url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('photos', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('grocery store', 'grocery store'), ('primary care', 'primary care'), ('bank', 'bank'), ('park', 'park'), ('mental health service', 'mental health'), ('emergency service', 'emergency service'), ('pharmacy', 'pharmacy')], max_length=24)),
            ],
        ),
    ]
