# Generated by Django 4.0.5 on 2022-07-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('grocery store', 'grocery store'), ('primary care', 'primary care'), ('bank', 'bank'), ('park', 'park'), ('mental health service', 'mental health'), ('emergency service', 'emergency service'), ('pharmacy', 'pharmacy'), ('post office', 'post office'), ('trail', 'trail'), ('public transportation', 'public transportation'), ('fedex', 'fedex'), ('ups', 'ups')], max_length=24),
        ),
    ]
